### PR TITLE
fix video_count and subscriber_count type

### PR DESCRIPTION
**Pull request by yuisue**
I get type error on calling `getChannels` function, it seems had changed video_count / subscriber_count type from sting to int.
image

### CODE REVIEW

**Comment by getBoolean** [comment]
Looks good at a glance. I'll test it tonight since CI seems to not be working.

**Review by getBoolean — APPROVED** [review]

**Comment by getBoolean** [comment]
Ah I see, the CI was working, I just needed to approve it to run

**Comment by getBoolean** [comment]
Thanks for the PR, I should probably set up a CRON workflow to catch this kind of thing.

**Comment by getBoolean** [comment]
Published as `2.0.0` https://pub.dev/packages/dart_holodex_api

**Comment by yuisue** [comment]
> Published as `2.0.0` https://pub.dev/packages/dart_holodex_api

Thanks for update! I'll take a check for release version.

**Pull request merged**
